# Fourmolu configuration for euler-problems
# See https://github.com/fourmolu/fourmolu for more options

indentation: 2
function-arrows: trailing
comma-style: leading
import-export-style: leading
indent-wheres: true
record-brace-space: true
newlines-between-decls: 1
haddock-style: single-line
let-style: auto
in-style: right-align
respectful: true
fixities: []
reexports: []