name: euler-problems
version: 1.0.0
github: "your-username/euler-problems"
license: MIT
author: "Your Name"
maintainer: "your-email@example.com"
copyright: "2024 Your Name"

extra-source-files:
- README.md
- LICENSE

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Euler4
    - Euler27
  dependencies:
    - containers

tests:
  euler-tests:
    main: test_euler.hs
    source-dirs: src
    dependencies:
      - euler-problems